language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t yoon7548/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true yoon7548/react-test-app npm test

after_success:
    - docker build -t yoon7548/docker-frontend ./frontend
    - docker build -t yoon7548/docker-backend ./backend
    - docker build -t yoon7548/docker-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push yoon7548/docker-frontend
    - docker push yoon7548/docker-backend
    - docker push yoon7548/docker-nginx
