version: '3'
services:
    frontend:
        image: yoon7548/docker-frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true
        mem_limit: 128m

    nginx:
        restart: always
        image: yoon7548/docker-nginx
        ports:
            - '80:80'

    backend:
        image: yoon7548/docker-backend
        container_name: app_backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        mem_limit: 128m
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: daew09070515
            MYSQL_DATABASE: myapp
            MYSQL_PORT: 330
